-- DANGEROUS: THIS WILL DELETE ALL EXISTING DATA
-- Run this in the Supabase SQL Editor to reset your project to a clean, public state.

-- 1. DROP EXISTING TABLES (Reverse Order of Dependencies)
DROP TABLE IF EXISTS public.tasks;
DROP TABLE IF EXISTS public.team_members;
DROP TABLE IF EXISTS public.projects;

-- 2. CREATE TABLES

-- Projects Table
CREATE TABLE public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Team Members Table (No Auth/Email required for public version, but keeping structure)
CREATE TABLE public.team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    designation TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tasks Table
CREATE TABLE public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    project TEXT,
    owner TEXT,
    priority TEXT DEFAULT 'Medium',
    status TEXT DEFAULT 'Pending' NOT NULL,
    assigned_date DATE DEFAULT CURRENT_DATE,
    promise_date DATE,
    comments TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. ENABLE ROW LEVEL SECURITY (RLS)
-- We enable it, but we will add policies to allow PUBLIC access.
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- 4. CREATE PUBLIC POLICIES (Allow Anonymous Access)

-- Tasks
CREATE POLICY "Public Enable Read Access" ON public.tasks FOR SELECT USING (true);
CREATE POLICY "Public Enable Insert Access" ON public.tasks FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Enable Update Access" ON public.tasks FOR UPDATE USING (true);
CREATE POLICY "Public Enable Delete Access" ON public.tasks FOR DELETE USING (true);

-- Team Members
CREATE POLICY "Public Enable Read Access" ON public.team_members FOR SELECT USING (true);
CREATE POLICY "Public Enable Insert Access" ON public.team_members FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Enable Update Access" ON public.team_members FOR UPDATE USING (true);
CREATE POLICY "Public Enable Delete Access" ON public.team_members FOR DELETE USING (true);

-- Projects
CREATE POLICY "Public Enable Read Access" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Public Enable Insert Access" ON public.projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Enable Update Access" ON public.projects FOR UPDATE USING (true);
CREATE POLICY "Public Enable Delete Access" ON public.projects FOR DELETE USING (true);

-- 5. SEED INITIAL DATA (Optional)
INSERT INTO public.projects (name) VALUES ('Website Redesign'), ('Mobile App');
INSERT INTO public.team_members (name, designation) VALUES ('Alice', 'Developer'), ('Bob', 'Designer');
