-- ACTION TRACKER 3.0 SCHEMA (Many-to-Many / Multi-Team)
-- Run this in Supabase SQL Editor. It will RESET your database structure.

-- 1. CLEANUP (Drop existing)
DROP TABLE IF EXISTS public.tasks;
DROP TABLE IF EXISTS public.team_members; -- The "Virtual" members
DROP TABLE IF EXISTS public.projects;
DROP TABLE IF EXISTS public.department_members; -- NEW
DROP TABLE IF EXISTS public.profiles;
DROP TABLE IF EXISTS public.departments;

-- 2. CREATE TABLES

-- Departments (The "Teams")
CREATE TABLE public.departments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    access_code TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Profiles (Global User Data - No Department Link Here Anymore)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    full_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Department Members (Junction Table: User <-> Department)
CREATE TABLE public.department_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) NOT NULL,
    department_id UUID REFERENCES public.departments(id) NOT NULL,
    role TEXT DEFAULT 'Member', -- 'Admin' or 'Member' (Scoped to this team)
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, department_id) -- Prevent duplicate joining
);

-- Projects
CREATE TABLE public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id UUID REFERENCES public.departments(id) NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Team Members (Virtual/Offline people)
CREATE TABLE public.team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id UUID REFERENCES public.departments(id) NOT NULL,
    name TEXT NOT NULL,
    email TEXT,
    designation TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tasks
CREATE TABLE public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id UUID REFERENCES public.departments(id) NOT NULL,
    description TEXT NOT NULL,
    project TEXT,
    owner TEXT,
    priority TEXT DEFAULT 'Medium',
    status TEXT DEFAULT 'Pending' NOT NULL,
    assigned_date DATE DEFAULT CURRENT_DATE,
    promise_date DATE,
    comments TEXT,
    completed_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. ENABLE RLS
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.department_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- 4. RLS POLICIES

-- Helper: Get list of department IDs the current user belongs to
CREATE OR REPLACE FUNCTION get_my_department_ids()
RETURNS TABLE (dept_id UUID) AS $$
  SELECT department_id FROM public.department_members WHERE user_id = auth.uid();
$$ LANGUAGE sql SECURITY DEFINER;

-- DEPARTMENTS
-- Allow reading only if you are a member
CREATE POLICY "Read my departments" ON public.departments FOR SELECT TO authenticated 
USING (id IN (SELECT department_id FROM public.department_members WHERE user_id = auth.uid()));

-- Allow creating new departments (for Sign Up)
CREATE POLICY "Create departments" ON public.departments FOR INSERT TO authenticated WITH CHECK (true);

-- Allow finding department by code (needed for Join logic)
CREATE POLICY "Find department by code" ON public.departments FOR SELECT TO authenticated 
USING (true); 

-- PROFILES
-- Read/Write own profile
CREATE POLICY "Manage own profile" ON public.profiles FOR ALL TO authenticated 
USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- Read profiles of people in my teams
CREATE POLICY "Read team profiles" ON public.profiles FOR SELECT TO authenticated 
USING (id IN (
    SELECT user_id FROM public.department_members WHERE department_id IN (
        SELECT department_id FROM public.department_members WHERE user_id = auth.uid()
    )
));

-- DEPARTMENT MEMBERS (The "Membership" Cards)
-- Read: See who is in my teams
CREATE POLICY "Read team memberships" ON public.department_members FOR SELECT TO authenticated 
USING (department_id IN (SELECT get_my_department_ids()));

-- Insert: Add MYSELF to a team (Join flow)
CREATE POLICY "Join team" ON public.department_members FOR INSERT TO authenticated 
WITH CHECK (user_id = auth.uid());

-- DATA TABLES (Tasks, Projects, etc)
-- Read/Write if record belongs to one of my teams
-- Note: Frontend must enforce sending the 'active' department_id

CREATE POLICY "Access Projects" ON public.projects FOR ALL TO authenticated
USING (department_id IN (SELECT get_my_department_ids()));

CREATE POLICY "Access Virtual Members" ON public.team_members FOR ALL TO authenticated
USING (department_id IN (SELECT get_my_department_ids()));

CREATE POLICY "Access Tasks" ON public.tasks FOR ALL TO authenticated
USING (department_id IN (SELECT get_my_department_ids()));
