-- ACTION TRACKER 2.0 SCHEMA (Multi-Tenant)
-- Run this in Supabase SQL Editor. It will RESET your database.

-- 1. CLEANUP (Drop existing)
DROP TABLE IF EXISTS public.tasks;
DROP TABLE IF EXISTS public.team_members;
DROP TABLE IF EXISTS public.projects;
DROP TABLE IF EXISTS public.profiles;
DROP TABLE IF EXISTS public.departments;

-- 2. CREATE TABLES

-- Departments (The "Organizations")
CREATE TABLE public.departments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    access_code TEXT NOT NULL UNIQUE, -- The "Team Code"
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Profiles (Links User -> Department)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) PRIMARY KEY, -- Matches Auth User ID
    full_name TEXT,
    department_id UUID REFERENCES public.departments(id),
    role TEXT DEFAULT 'Member', -- 'Admin' or 'Member'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Projects
CREATE TABLE public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id UUID REFERENCES public.departments(id) NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Team Members (Virtual representations of people in the team, not necessarily login users)
-- In V2, we might want to link these to real profiles eventually, but for now keep as is, just scoped.
CREATE TABLE public.team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id UUID REFERENCES public.departments(id) NOT NULL,
    name TEXT NOT NULL,
    designation TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tasks
CREATE TABLE public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id UUID REFERENCES public.departments(id) NOT NULL,
    description TEXT NOT NULL,
    project TEXT, -- Keeping as text based on original design, or could link to projects.name
    owner TEXT, -- Text name of owner
    priority TEXT DEFAULT 'Medium',
    status TEXT DEFAULT 'Pending' NOT NULL,
    assigned_date DATE DEFAULT CURRENT_DATE,
    promise_date DATE,
    comments TEXT,
    completed_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. ENABLE RLS
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- 4. RLS POLICIES (The Magic Separation)

-- Helper function to get current user's department
-- This makes policies cleaner.
CREATE OR REPLACE FUNCTION get_my_department_id()
RETURNS UUID AS $$
  SELECT department_id FROM public.profiles WHERE id = auth.uid() LIMIT 1;
$$ LANGUAGE sql SECURITY DEFINER;

-- DEPARTMENTS:
-- Everyone can read departments (to check codes), but usually we filter this better.
-- For simplicity: Allow reading all (needed for "Join" check), but strictly control writes.
CREATE POLICY "Enable read access for authenticated users" ON public.departments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users" ON public.departments FOR INSERT TO authenticated WITH CHECK (true); 

-- PROFILES:
-- Users can read profiles in their own department.
-- Users can insert/update their OWN profile.
CREATE POLICY "Read own department profiles" ON public.profiles FOR SELECT TO authenticated 
USING (department_id = get_my_department_id() OR id = auth.uid());

CREATE POLICY "Manage own profile" ON public.profiles FOR ALL TO authenticated 
USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- PROJECTS, TEAM_MEMBERS, TASKS:
-- Standard isolation: Only access if department_id matches user's department.

-- Projects
CREATE POLICY "Department Isolation" ON public.projects FOR ALL TO authenticated
USING (department_id = get_my_department_id())
WITH CHECK (department_id = get_my_department_id());

-- Team Members
CREATE POLICY "Department Isolation" ON public.team_members FOR ALL TO authenticated
USING (department_id = get_my_department_id())
WITH CHECK (department_id = get_my_department_id());

-- Tasks
CREATE POLICY "Department Isolation" ON public.tasks FOR ALL TO authenticated
USING (department_id = get_my_department_id())
WITH CHECK (department_id = get_my_department_id());

-- 5. STORAGE BUCKETS (If we add file attachments later)
-- insert into storage.buckets (id, name) values ('files', 'files');
